# Image mappings and synonyms to improve matching

brands:
  - name: roborock
    aliases: ["robo rock", "s7", "roborock s7", "s8", "roborock s7 maxv"]
  - name: roomba
    aliases: ["irobot", "i-robot", "roomba j7", "j7+"]
  - name: tp-link
    aliases: ["tplink", "kasa", "hs103", "hs110"]
  - name: philips hue
    aliases: ["hue", "philips-hue", "a19"]
  - name: google nest
    aliases: ["nest", "nest learning"]

categories:
  robot_vacuums:
    synonyms: ["robot vacuum", "robovac", "vacuum robot"]
  security_cameras:
    synonyms: ["security camera", "cctv", "surveillance"]
  smart_plugs:
    synonyms: ["smart plug", "smart outlet", "wifi plug"]
  smart_bulbs:
    synonyms: ["smart bulb", "smart light", "led bulb"]
  smart_thermostats:
    synonyms: ["smart thermostat", "thermostat"]

scenes:
  installation: ["install", "installation", "setup"]
  comparison: ["compare", "comparison", "vs"]
  compatibility: ["compatibility", "matter", "thread"]
