name: Daily Content Generation - Simple & Reliable

on:
  schedule:
    # Run at 1:00 AM UTC daily (9:00 AM China time)
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: false
        default: '1'
        type: string
      force_generation:
        description: 'Force generation even if recent articles exist'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create environment file
        run: |
          echo "GOOGLE_ADSENSE_ID=${{ secrets.GOOGLE_ADSENSE_ID }}" >> .env
          echo "AMAZON_AFFILIATE_TAG=${{ secrets.AMAZON_AFFILIATE_TAG }}" >> .env
          echo "GOOGLE_ANALYTICS_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}" >> .env

      - name: Prepare content generation
        id: check_needed
        run: |
          # Always generate content - ensure daily article creation
          echo "should_generate=true" >> $GITHUB_OUTPUT
          if [ "${{ github.event.inputs.force_generation }}" = "true" ]; then
            echo "reason=forced_generation" >> $GITHUB_OUTPUT
          else
            echo "reason=daily_content_schedule" >> $GITHUB_OUTPUT
          fi
          
          # Set target article count (default 1, can be overridden)
          article_count="${{ github.event.inputs.article_count || '1' }}"
          echo "target_count=$article_count" >> $GITHUB_OUTPUT

      - name: Generate articles
        run: |
          python scripts/generate_daily_content.py \
            --count "${{ steps.check_needed.outputs.target_count }}" \
            --output-dir content/articles

      - name: Quality check
        run: |
          python scripts/quality_check.py content/articles/

      - name: Commit new content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add content/articles/*.md
          
          if ! git diff --staged --quiet; then
            current_date=$(date '+%Y-%m-%d')
            git commit -m "Auto: Daily content update - $current_date - Generated with Claude Code AI Assistant - Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
          fi

      - name: Send Telegram notification
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ "${{ secrets.TELEGRAM_BOT_TOKEN }}" != "" ] && [ "${{ secrets.TELEGRAM_CHAT_ID }}" != "" ]; then
            python scripts/notify_telegram.py \
              --type daily_content \
              --status "${{ job.status }}" \
              --generated "${{ steps.check_needed.outputs.should_generate }}" \
              --reason "${{ steps.check_needed.outputs.reason }}"
          fi